In [1]:
import random
import heapq
from dataclasses import dataclass, field
from typing import List, Tuple, Callable, Any, Set
import numpy as np
from time import time
from tabulate import tabulate
import threading
import collections
from math import ceil
from enum import Enum
from functools import partial
from copy import deepcopy
from collections import deque


In [2]:

class LightsOutPuzzle:
    def __init__(self, board: List[List[int]], keylist):
        self.board = np.array(board, dtype=np.uint8)
        self.size = len(board)
        self.keys = keylist
        self.depth = 0

    def toggle(self, x, y):
        for dx, dy in [(0, 0), (1, 0), (-1, 0), (0, 1), (0, -1)]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < self.size and 0 <= ny < self.size:
                self.board[nx, ny] ^= 1

    def is_solved(self):
        return np.all(self.board == 0)

    def get_moves(self):
        return [(x, y) for x in range(self.size) for y in range(self.size)]

    def __str__(self):
        return '\n'.join(' '.join(str(cell) for cell in row) for row in self.board)


In [3]:
def create_random_board(size: int,  seed: int, num_toggles: int = None):
    random.seed(time() if seed is None else seed)

    board = [[0 for _ in range(size)] for _ in range(size)]
    puzzle = LightsOutPuzzle(board, [])

    if num_toggles is None:
        num_toggles = random.randint(1, size * size)

    for _ in range(num_toggles):
        x = random.randint(0, size - 1)
        y = random.randint(0, size - 1)
        puzzle.toggle(x, y)

    return puzzle.board

In [4]:
def show_solution(
    puzzle: LightsOutPuzzle,
    solution: List[Tuple[int, int]],
    algorithm_name: str,
    nodes_visited: int,
    show_steps: bool = False,
):
    print(f"\nSolving with {algorithm_name}:")
    if solution is None:
        print("No solution found.")
        return
    print(f"Solution: {solution}")
    print(f"Nodes visited: {nodes_visited}")
    if show_steps:
        print("\nSolution steps:")
        for i, move in enumerate(solution):
            print(f"\nStep {i+1}: Toggle position {move}")
            puzzle.toggle(*move)
            print(puzzle)
        print(
            "\nFinal state (solved):"
            if puzzle.is_solved()
            else "\nFinal state (not solved):"
        )
        print(puzzle)

In [5]:
tests = [
    create_random_board(3, 42),
    create_random_board(3, 41),
    create_random_board(3, 42, 5),
    create_random_board(4, 42),
    create_random_board(4, 41),
    create_random_board(4, 42, 5),
    create_random_board(5, 42),
    create_random_board(5, 41),
    create_random_board(5, 42, 5),
]

In [6]:
# TODO: Must return a list of tuples and the number of visited nodes
def bfs_solve(puzzle: LightsOutPuzzle) -> Tuple[List[Tuple[int, int]], int]:    
    frontier = [puzzle]
    explored = []
    if frontier[0].is_solved():
        return [], 1
    
    while (frontier):
        
        node = frontier.pop(0)
        explored.append(node)
        for (x,y) in node.get_moves():
            flag1 = 0
            flag2 = 0
            new_state = deepcopy(node)
            new_state.toggle(x, y)
            new_state.keys.append((x,y))
            for pz in explored :
                if (pz.board.tolist() == new_state.board.tolist()): 
                    flag1 = 1
            for pz in frontier :
                if (pz.board.tolist() == new_state.board.tolist()): 
                    flag2 = 1
            if flag1 == 0 and flag2 == 0 :
                if(new_state.is_solved()):
                    return new_state.keys, len(explored)
                frontier.append(new_state)

    return [], 0

In [7]:
# TODO: Must return a list of tuples and the number of visited nodes
def ids_solve(puzzle: LightsOutPuzzle) -> Tuple[List[Tuple[int, int]], int]:
    limit_of_depth = 0
    if puzzle.is_solved():
        return [], 1
    ex2 = []
    while(1):
        frontier = [puzzle]
        explored = []
        while(frontier):
            
            node = frontier.pop()
            explored.append(node)
            ex2.append(node)
            for (x,y) in node.get_moves():
                flag2 = 0
                flag1 = 0
                new_state = deepcopy(node)
                new_state.toggle(x, y)
                new_state.keys.append((x,y))
                new_state.depth += 1
                for pz in explored :
                    if (pz.board.tolist() == new_state.board.tolist()): 
                        flag1 = 1
                for pz in frontier :
                    if (pz.board.tolist() == new_state.board.tolist()): 
                        flag2 = 1
                if flag1 == 0 and flag2 == 0 :
                    if new_state.depth <= limit_of_depth +1:
                        frontier.append(new_state)
                    if(new_state.is_solved()):
                        return new_state.keys, len(ex2)+1
        limit_of_depth += 1          
        

In [8]:
# TODO: Must return a list of tuples and the number of visited nodes
def astar_solve(puzzle: LightsOutPuzzle, heuristic: Callable[[LightsOutPuzzle], int]) -> Tuple[List[Tuple[int, int]], int]:
    frontier = []
    explored = []
    if puzzle.is_solved():
        return [], 1
    cnt = 0
    heapq.heappush(frontier,(heuristic(puzzle), cnt, puzzle))
    while (frontier):
        h,c,node = heapq.heappop(frontier)
        explored.append(node)
        if(node.is_solved()):
            return node.keys, len(explored)
        for (x,y) in node.get_moves():
            flag = 0
            new_state = deepcopy(node)
            new_state.toggle(x, y)
            new_state.keys.append((x,y))
            for pz in explored :
                    if (pz.board.tolist() == new_state.board.tolist()): 
                        flag = 1
            if flag == 0:
                cnt += 1
                heapq.heappush(frontier,(heuristic(new_state)+len(new_state.keys), cnt, new_state))

In [9]:
# TODO: Implement heuristic functions and store them in the list

def heuristic1(puzzle: LightsOutPuzzle):
  sum = 0
  for row in puzzle.board:
    for i in row:
      sum += i
  return sum

def heuristic2(puzzle: LightsOutPuzzle):
    sum1 = 0
    sum1 = sum(sum(row) for row in puzzle.board)/5
    return sum1

heuristics = [heuristic1, heuristic2]

In [10]:
# TODO: Implement weighted heuristic functions and store them in the list
def weighted_heuristic1(puzzle: LightsOutPuzzle, alpha = 5):
  return heuristic1(puzzle) * alpha

def weighted_heuristic2(puzzle: LightsOutPuzzle, alpha = 5):
  return heuristic2(puzzle) * alpha

weighted_heuristics = [weighted_heuristic1, weighted_heuristic2]

# TODO: assign 2 weights you wanna run
weights = [2, 5]

In [11]:
class SearchStatus(Enum):
    SOLVED = "Solved"
    TIMEOUT = "Timeout"
    NO_SOLUTION = "No Solution"

@dataclass
class SearchResult:
    result: SearchStatus
    solution: Any = None
    nodes_visited: int = None
    time: float = None

    def __str__(self):
        output = f"Result: {self.result.value}\n"
        if self.result == SearchStatus.SOLVED:
            output += f"Solution: {self.solution}\n"
        if self.result != SearchStatus.TIMEOUT:
            output += f"Nodes Visited: {self.nodes_visited}\n"
            output += f"Time Taken: {self.time:.3f} seconds\n"

        return output


DEFAULT_SEARCH_RESULT = SearchResult(SearchStatus.TIMEOUT, None, None, float("inf"))

In [12]:
def run_searches(func: Callable, args: Any, time_limit: float = 60.0, name: str = "") -> SearchResult:
    result = []

    def target():
        try:
            solution, nodes_visited = func(*args)
            result.append((solution, nodes_visited))
        except Exception as e:
            result.append(e)

    thread = threading.Thread(target=target)
    thread.start()

    start_time = time()
    thread.join(timeout=time_limit)

    if thread.is_alive() or not result:
        print(f"\nTime limit of {time_limit} seconds exceeded for {name}")
        return SearchResult(SearchStatus.TIMEOUT)

    if isinstance(result[0], Exception):
        raise result[0]

    solution, nodes_visited = result[0]
    show_solution(args[0], solution, name, nodes_visited)
    time_taken = time() - start_time
    return SearchResult(SearchStatus.SOLVED if solution else SearchStatus.NO_SOLUTION, solution, nodes_visited, time_taken)

In [13]:
def run_test(test: List, heuristics: List[Callable[[Any], int]], time_limit: float = 60.0):

    print(f"Running test:\n {test}")

    puzzle = LightsOutPuzzle(test, [])

    bfs_result = run_searches(bfs_solve, (deepcopy(puzzle),), name="BFS", time_limit=time_limit)
    ids_result = run_searches(ids_solve, (deepcopy(puzzle),), name="IDS", time_limit=time_limit)

    astar_results = []
    for heuristic in heuristics:
        astar_results.append(
            run_searches(
                astar_solve,
                (deepcopy(puzzle), heuristic),
                name=f"A*({heuristic.__name__})",
                time_limit=time_limit,
            )
        )

    weighted_astar_results = []
    for heuristic in weighted_heuristics:
        for weight in weights:
          weighted_astar_results.append(
              run_searches(
                  astar_solve,
                  (deepcopy(puzzle), partial(heuristic, alpha = weight)),
                  name=f"weighted A*({heuristic.__name__}, alpha = {weight})",
                  time_limit=time_limit,
              )
          )

    print("\n-------------------------------\n")

    return (
        test,
        bfs_result,
        ids_result,
        *astar_results,
        *weighted_astar_results
    )

In [14]:
results: List[Tuple[str, SearchResult, SearchResult, SearchResult, SearchResult]] = []

for test in tests:
    results.append(run_test(test, heuristics, 180))

Running test:
 [[1 1 1]
 [1 1 1]
 [1 0 0]]

Solving with BFS:
Solution: [(0, 2), (1, 0)]
Nodes visited: 4

Solving with IDS:
Solution: [(1, 0), (0, 2)]
Nodes visited: 8

Solving with A*(heuristic1):
Solution: [(1, 0), (0, 2)]
Nodes visited: 4

Solving with A*(heuristic2):
Solution: [(1, 0), (0, 2)]
Nodes visited: 8

Solving with weighted A*(weighted_heuristic1, alpha = 2):
Solution: [(1, 0), (0, 2)]
Nodes visited: 6

Solving with weighted A*(weighted_heuristic1, alpha = 5):
Solution: [(1, 0), (0, 2)]
Nodes visited: 6

Solving with weighted A*(weighted_heuristic2, alpha = 2):
Solution: [(1, 0), (0, 2)]
Nodes visited: 4

Solving with weighted A*(weighted_heuristic2, alpha = 5):
Solution: [(1, 0), (0, 2)]
Nodes visited: 4

-------------------------------

Running test:
 [[1 1 0]
 [1 0 0]
 [1 1 1]]

Solving with BFS:
Solution: [(0, 0), (0, 1), (1, 0), (1, 1), (1, 2)]
Nodes visited: 137

Solving with IDS:
Solution: [(1, 1), (1, 0), (0, 1), (1, 2), (0, 0)]
Nodes visited: 567

Solving with A*

In [15]:
table_data: List[List[str]] = []

for result in results:
    table_data.append(
        [
            "\n".join(" ".join(str(cell) for cell in row) for row in result[0]),
            str(result[1]),
            str(result[2]),
        ]
    )
    for i in range(len(heuristics)):
        table_data[-1].append(str(result[3 + i]))

    for i in range(len(weighted_heuristics)):
        for j in range(len(weights)):
          table_data[-1].append(str(result[3 + len(heuristics) + i * 2 + j]))

    table_data.append("\n\n\n")

if table_data[-1] == "\n\n\n":
    table_data.pop()

print(len(table_data))
print("Results:")
print(
    tabulate(
        table_data,
        headers=[
            "Test",
            "BFS",
            "IDS",
            *[f"A* ({heuristic.__name__})" for heuristic in heuristics],
            *[f"Weighted A* ({heuristic.__name__}, alpha = {weight})" for heuristic in weighted_heuristics for weight in weights]
        ],
        floatfmt=".3f",
        numalign="center",
        stralign="center",
        tablefmt="grid",
    )
)

17
Results:
+-----------+----------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------+----------------------------------------------------+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+--------------------------------------------------------------------+
|   Test    |                        BFS                         |                        IDS                         |                          A* (heuristic1)                           |                  A* (heuristic2)                   |                    Weighted A* (weighted_heuristic1, alpha = 2)                    |                                            Weighted A* (weighted_heuristic1, al